service:
  name: PLUTO MANAGEMENT SERVICE
  production: false
  port: 8080

database:
  dialect: mysql
  url: root:root@tcp(localhost:3307)/pluto?parseTime=true

redis:
  url: localhost:6379

minio:
  endpoint: play.min.io
  accesskey: Q3AM3UQ867SPQQA43P2F
  secretkey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  usessl: tru
