service:
  name: PLUTO MANAGEMENT SERVICE
  production: false
  port: 8080

database:
  dialect: mysql
  url: root:root@tcp(localhost:3307)/pluto?parseTime=true

redis:
  url: localhost:6379

minio:
  scheme: http
  endpoint: 165.22.249.91:9000
  accesskey: pluto
  secretkey: dhQk@3slyUi
  usessl: false
  bucketname: plutos3
