service:
  name: PLUTO MANAGEMENT SERVICE
  production: false
  port: 8080

database:
  dialect: mysql
  url: root:root@tcp(localhost:3307)/pluto?parseTime=true

redis:
  url: localhost:6379

minio:
  scheme: http
  endpoint: localhost:9000
  accesskey: pluto
  secretkey: dhQk@3sl
  usessl: false
